### ISSUE TITLE
igoring docker-compose setting container_name:

### ISSUE THREAD

**Issue by frank3427** [VSChina/compose-to-manifest#3] opened 2019-09-25 03:58 UTC
when converting the docker-compose.yml file, the container_name: setting in the file is being ignored. the container is named to the service name when is should be from container_name: value

**Comment by frank3427** [comment] 2019-10-07 16:38
so I am looking for a way to set the container name to be different from the module name.
in docker-compose when you define a service you can set the container name 
container_name: name201805090000.999
is there an equivalent setting in Manifest that one can use to set the name of the container for a module?

**Comment by shizn** [comment] 2019-10-08 00:32
@formulahendry

**Comment by shizn** [comment] 2019-10-08 00:34
@frank3427 not sure if you are looking for this but you can have a different name in the green box in module.json file.
![image](https://user-images.githubusercontent.com/3619378/66358678-bb309e00-e928-11e9-80a8-89199506eeee.png)

**Comment by frank3427** [comment] 2019-10-08 17:33
that is not my issue,
looking at your screen shot, right under modules you have SampleModule that
label will become the container name when deployed, I need a way to set the
container name to a different name modulexxx.yyy can not find any way of
doing this in docker-compose.yml one can just container_name: modulexxx.yyy

**Comment by lijunchen** [comment] 2019-10-11 06:01
Current only support fields in [ContainerConfig's constructor](https://github.com/docker/docker-py/blob/8077d80118d289625248051d608a15cd34b19c27/docker/types/containers.py#L556), I guess there is no field in [ContainerCreate API](https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate) about container name.

**Comment by frank3427** [comment] 2019-10-11 14:00
what about
https://docs.docker.com/engine/api/v1.30/#operation/ContainerRename

**Comment by frank3427** [comment] 2019-10-11 14:04
what about this at the top of container create

 name
string /?[a-zA-Z0-9_-]+

Assign the specified name to the container. Must match /?[a-zA-Z0-9_-]+.

**Comment by typeli** [comment] 2019-10-11 15:04
Hi, I noticed that, but it isn't a part of request body. As far as I know, createOptions in deployment file should conform with docker engine API. This maybe an issue of iotedge, but I don't have enough time to investigate it. I have finished my internship at the end of Aug. Recently, I was notified that I didn't get return offer. I am very disappointed in myself. But I have to cheer up and need to focus on hunting another job. I am really sorry that I won't be able maintain this project in the near future.

**Comment by frank3427** [comment] 2019-10-11 16:16
Using the --name Parameter

By default, Docker will create a unique name for each container started.
The names are generated from a list of descriptions (ie, “boring” or
“hungry”) and famous scientists or hackers (ie, Wozniak, Ritchie). It’s
possible however, to specify a name for our container. We can do so by
simply using the --name parameter when executing docker run.

**Comment by konichi3** [comment] 2021-01-09 01:17
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed as completed by konichi3** 2021-01-09 01:17 UTC
